### PR TITLE
Add dotnet 8 support

### PR DESCRIPTION
**Pull request by Goltom**
- Add support for .net8
- IPNetwork renamed to IPNetwork2
- Update nuget package Microsoft.NET.Test.Sdk
- Unittest fix

### CODE REVIEW

**Comment by lduchosal** [comment]
Well, everyone tracking ipnetwork nuget will get its build broken... 
This should be upgrade a new major version, v 3.0.0 ...

**Comment by Goltom** [comment]
@lduchosal 
I think you have to update the .NET SDK on the build server (ERROR: ... does not support targeting .NET 8.0) or reference the right one in the build pipeline (YAML file).
Something like:
`steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 8 sdk'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        includePreviewVersions: true`

**Comment by lduchosal** [comment]
Thanks for you help

**Comment by Maxwell175** [comment]
The better solution should have been to move everything out of the System namespace entirely. Because it is intended to only be used by Microsoft.

**Comment by lduchosal** [comment]
Sure, PR welcome ! @Maxwell175

**Comment by Goltom** [comment]
> Thanks for you help

You are welcome :)

**Pull request merged**
